sudo: required
language: python
jdk: openjdk8

python:
  - "3.6"

services:
  - docker

before_install:
  - docker pull quay.io/icgc-argo/dna-seq-processing-tools:0.1.1

install:
  - "pip install -r tests/requirements-test.txt"
  # Install Nextflow
  - mkdir /tmp/nextflow
  - cd /tmp/nextflow
  - wget -qO- get.nextflow.io | bash
  - chmod 755 /tmp/nextflow/nextflow
  - sudo ln -s /tmp/nextflow/nextflow /usr/local/bin/nextflow

script: 
  - pytest -v
