language: python

python:
  - "3.6"

services:
  - docker

before_install:
  - docker pull quay.io/pancancer/dna-seq-processing:0.1.0

install:
  - "pip install -r tests/requirements-test.txt"

script: 
  - pytest -v
